### PR TITLE
Bug fix: Add duplicate note check where capital is considered

### LINKED ISSUE #267: Bug: Notes feature does not check if 2 notes are similar alpha numerically
I think this is an issue which should be solved as in PE people might fault us for this.

image

Essentially they are the same note but yes no one will do this but I feel this might be something others might point out as a bug

### PR DESCRIPTION
**Pull request by ITLimJiaWei**
Closes #267
Fixs duplicate note check for lowercase + uppercase as well as update message usages of add, edit and delete notes

### CODE REVIEW

**Review by joeltio — CHANGES_REQUESTED** [review]
I suggest this to be implemented on the `Note` level. So that the change is enforced by all commands.

i.e.
```patch
diff --git a/src/main/java/bizbook/model/person/Note.java b/src/main/java/bizbook/model/person/Note.java
index 15a4362f..bcb44179 100644
--- a/src/main/java/bizbook/model/person/Note.java
+++ b/src/main/java/bizbook/model/person/Note.java
@@ -44,13 +44,13 @@ public class Note {
 
         Note otherNotes = (Note) other;
 
-        return note.equals(otherNotes.note);
+        return note.toLowerCase().equals(otherNotes.note.toLowerCase());
     }
 
     @Override
     public int hashCode() {
         // use this method for custom fields hashing instead of implementing your own
-        return Objects.hash(note);
+        return Objects.hash(note.toLowerCase());
     }
 
     /**

```

**Comment by joeltio** [comment]
Remember to add tests too!

**Review by Nicholas-Cheng-De-Fei — APPROVED** [review]
Other than what was mentioned, LGTM

**Review by joeltio — APPROVED** [review]
LGTM

**Pull request merged**
