### PR TITLE
Add codecov badge

### LINKED ISSUE #95: Add Codecov badge to README
Since we have Codecov set-up we might as well add the badge to our README as mentioned [here](https://se-education.org/guides/tutorials/codecov.html)

### PR DESCRIPTION
**Pull request by joeltio**
Closes #95

### CODE REVIEW

**Review by Nicholas-Cheng-De-Fei — APPROVED** [review]
Looks good to merge, the link does work and it links to the team project codecov page

**Review by KennethTeo2002 — APPROVED** [review]
LGTM.

**Review by ITLimJiaWei — APPROVED** [review]
LGTM pending conflict to be resolved.

**Review by Nicholas-Cheng-De-Fei — APPROVED** [review]
LGTM

**Pull request merged**
